#_SDF1 Example Python Automation
#_ver 0.1
#_class user,common,example encoder script,python,hisurfadvisory,1,string

import macross as ms
from macross import macross


## The macross library replicates most of MACROSS's powershell functions; some of these functions
## are redundant in python, but it helped me to use the same function names for MACROSS-specific
## code. Importing macross also carries over the global powershell variables like PROTOCULTURE
## and CALLER when they've already been set beforehand.

## In the debug menu, just type "python" and you can manually import macross in a python shell
## to view all its functions.

## In addition to macross, this environment provides these extra libraries*:
##  numpy, pandas, pypdf, pdfplumber, beautifulsoup, paramiko

## *tkinter is not available; you need to use system python for that library.


## Here we check if BASARA is being called by another diamond vs. from the main menu
if ms.CALLER:

    ## You can check the properties of a calling diamond using the LATTS object:
    LANGUAGE = ms.LATTS[ms.CALLER].lang

    ## If a powershell diamond called, it may have exported a PROTOCULTURE variable for us
    if LANGUAGE == 'powershell' and ms.PROTOCULTURE:

        ## The gerwalk function encodes & decodes both Base64 and Hexadecimal
        base64 = ms.gerwalk(ms.PROTOCULTURE,action='eb')
        processed = f"Encoded as Base64: {base64}"

        ## In python, MACROSS's collab function handles both retrieving and forwarding a PROTOCULTURE
        ## value back and forth with powershell by using disposable ".vf1" files in the local
        ## folder "macross_core\corefuncs\pynet\garbage_io". Here, we send the encoded text back to
        ## powershell for this demo by setting "response=True".
        ms.collab(Protoculture=processed,response=True)

    else:
        ## A python diamond will set PROTOCULTURE a little differently.
        ## Calling collab() without arguments will retrieve PROTOCULTURE values in the fields
        ## "target" or "results", provided that another diamond has already written these values
        ## to a PROTOCULTURE.vf1 file in the macross_core\corefuncs\pynet\garbage_io folder. The
        ## CALLER should also match this dictionary's "caller" field.
        ## macross.CALLER and macross.collab()["caller"] are generated by two different methods,
        ## but while macross.CALLER is the authoritative one, they should always match up.
        ## If they do not, you should consider everything in macross.collab() to be stale.
        assist = ms.collab()

        ## When a diamond is waiting for response, the "result" value will be "WAITING". Your
        ## diamond will update this value with the collab() function when it finishes its work.
        ## You must set "response=True" if your diamond is providing data instead of requesting it!
        ## (default is False)
        if assist["result"] == "WAITING":
            if ms.CALLER == assist["caller"]:                   ## <<-- You can double check if the PROTOCULTURE value is valid
                PROTOCULTURE = assist["target"]                 ## PROTOCULTURE should be in the target field
                base64 = ms.gerwalk(PROTOCULTURE,action='eb')  ## Encode whatever value was requested to be processed
                processed = f"Encoded as Base64: {base64}"      ## Format our response
                ms.collab(Protoculture=processed,response=True)       ## Send the response back to the python diamond


        ## A quick primer on shipping PROTOCULTURE between shells: from powershell -> python,
        ## MACROSS uses environment variables to set the macross.PROTOCULTURE value. From 
        ## python -> powershell or python -> python, it uses the t800 files. Not to get too confusing, 
        ## but in instances where you jump from python -> powershell -> back to python during the same 
        ## investigation, if powershell switches up the target value, macross.PROTOCULTURE becomes a 
        ## stale value, while macross.collab()['result'] is the new primary target. Clear as mud, right? 
        ## You shouldn't need to worry about any of this, it's all handled in the background, but you may 
        ## find that you want to tweak things for your use-case in the macross.py library.


else:

    ## MACROSS's psc() function executes commands via the os library; we'll clear the screen here. When
    ## executing a command that expects a response, you'd use cr= instead of cc= so that you can retrieve 
    ## the command's output.
    ms.psc(cc="cls")

    ## The minmay function displays one of 12 Macross ascii art images. Enter "screens" in the main menu to 
    ## view a slideshow of available art and their numbers.
    ms.minmay(7)
    ms.slp(2)
    ms.psc(cc="cls")

    ## MACROSS's skyWriter() function generates ascii-art text for your script titles
    title = ms.skyWriter(" basara")
    print("\n\n")

    ## MACROSS's w() function simplifies formatting the way text looks on screen by letting you
    ## colorize both the text and the background.
    ms.w(title,f="y")
    print("\n")

    ## yellow background with black text:
    ms.w(f"{' '*10}MACROSS automation flow:{' '*10}",f="k",b="y")


    ## The w() function also lets you format text with underlines (u=True) and inline/"no new lines"
    ## (i=True) if you need to use several different formats on the same line.
    ms.w("\n\n  1.",f="k",b="y",u=True,i=True)
    ms.w(""" Your automation does whatever it needs to do, but instead of coding extra tasks,
 you can search for existing automations within MACROSS written by yourself or your team
 to enrich or further process your script's data:""","g")
    ms.w("\n  2.",f="k",b="y",u=True,i=True)
    ms.w(""" The findDiamond function finds relevant scripts (diamonds), and the collab function
 forwards and retrieves data between them, with all automations giving priority to data
 assigned to the global variable PROTOCULTURE""","g")
    ms.w("\n  3.",f="k",b="y",i=True,u=True)
    ms.w("""  MACROSS provides multiple utilities to quickly reformat data onscreen or into
 reports & spreadsheets""","g")

    ms.w("\n\n This demo will send a filepath to powershell and ask for the file's hash.","g")
    ms.w(" Hit ENTER to select a file and begin the demo.","g")
    input()

    ## getFile() lets you open an explorer window to quickly get a filepath
    PROTOCULTURE = ms.getFile()

    ## Use MACROSS's findDiamond() to find other diamonds that can help enrich or transform your diamond's
    ## outputs. This function searches the LATTS object for diamond attributes based on filters you provide.
    ## This way, you can find multipe similar diamonds and loop calling each one to process the PROTOCULTURE
    ## data however needed.
    relevant_diamonds = ms.findDiamond(val="code example",lang="powershell",exact=False)

    print("\n\n\n")

    for r in relevant_diamonds:

        ## The LATTS object contains the macross class attributes for all of MACROSS's diamonds;
        ## you can use this to determine how to respond to a calling diamond.
        diamond = ms.LATTS[r].name
        huntval = ms.LATTS[r].valtype

        ms.w(" MACROSS provided the diamond ","g",i=True)
        ms.w(diamond,"c",i=True)
        ms.w("/","g",i=True)
        ms.w(f"'{huntval}'","m",i=True)
        ms.w(" to get","g")
        ms.w(f" info about the file. I'll call {diamond} now, standby...","g")

        ## Use the collab() function to send a PROTOCULTURE value to the powershell diamond for processing.
        ## This requires knowing what Diamond to call, and telling collab() that your diamond script is the CALLER.
        ms.collab(Diamond=r,Caller='BASARA',Protoculture=PROTOCULTURE)

        ## If you examine the PSEXAMPLE.ps1 script, in the section where it checks whether a $CALLER exists
        ## (around line 135) you'll see it performing a lookup on $CALLER (BASARA) to figure out what we want and
        ## whether it can reply directly, or if it has to use MACROSS's pyNET function to respond to python scripts.

        ## Call the collab function without args to retrieve the powershell response, which is
        ## a dictionary containing "caller", "target", "deculture" and "result" indexes.
        response = ms.collab()

        ## You can double check to make sure your request was responded to correctly by making sure your diamond's
        ## name is still the ID for the collab file.
        if response["caller"] != "BASARA":

            ## If you have logging enabled, the macross.errLog() function can log messages for you.
            ## View logs by typing "debug" in the main menu (the option is not available if logging is disabled)
            ms.errLog("WARN","PROTOCULTURE file was corrupted!")

        else:
            ms.w("\n ...Now we're back in python.\n","g")

            ms.w(" The powershell diamond should have given us back the filehash and creation timestamp:\n")
            labels = [" filename"," hash"," creation time"]

            for i,result in enumerate(response["result"]):

                ## The macross.screenResults function takes multiple lines, or large blocks of text, and
                ## **attempts** to format them in rows with up to 3 columns (the python implementation
                ## doesn't always work as well as the powershell version. I suck at math):
                ms.screenResults(labels[i],result)
            ms.screenResults()

            ## The python version of screenResults cannot write to file like the powershell version can.

    input("\n\n Be sure to review this python code's comments to see how MACROSS works.\n Hit ENTER to close this demo.")
    exit()








