#_sdf1 Example Powershell Automation
#_ver 0.1
#_class user,common,macross code example,powershell,HiSurfAdvisory,2,array


<#
    IMPORTANT!
    The first three lines of any MACROSS diamond automation MUST match the above!
    line 1 = brief description of your diamond; this displays in the main menu
    line 2 = the version number
    line 3 = the properties identifying your diamond to MACROSS:
        field 1 (.priv): the lowest level of privilege required to execute the diamond (user vs. admin)*
        field 2 (.access): if you enabled access controls, this needs to specify tier1/tier2/tier3, or "common"
            to make available to all tiers. Even if not using access control, this field is required. Note that
            this should be viewed as a convenience feature for auto-distribution to varied user's needs from a
            central repo; without enforced digital-signing this is easily bypassed.
        field 3 (.valtype): what kind of task or data your diamond works on
        field 4 (.lang): the diamond's language (only "powershell" or "python", no version numbers)
        field 5 (.auth): the author
        field 6 (.evalmax): the max number of parameters/arguments the diamond can evaluate (not counting
            the global $PROTOCULTURE value)
        field 7 (.rtype): what format your diamond responds in, if any

    For diamonds to collaborate on the same data, assign your working data to the var $Global:PROTOCULTURE and
    make sure all diamonds are coded to act on this data automatically when appropriate. This var will be 
    automatically killed by MACROSS when the main menu loads again.

    *You can have diamonds containing privileged functions that are still usable without them. Simply
    add a truthy check for $dyrl_ROBOTECH; if it is $true, the user does not have admin privilege to execute
    it.

#>


## Type "debug" in the main menu to see help files for all of MACROSS' utilities and test them out.



########################## TO WORK WITH PYTHON ####################################
<#
 The following code must be copied verbatim* into any powershell diamonds that
 expect to receive calls from python diamonds!

 $spiritia is not always required; it is any optional value that needs to be 
 processed instead of or in addition to $PROTOCULTURE.
 
 The $pythonsrc param IS required: it is the name of the calling python diamond.

 The spaceFold function loads all of MACROSS' resources in a temporary
 powershell session to process the python diamond's request.

    *$spiritia is not limited to python <--> powershell interactions; it can be used
    for any powershell diamond as this is a parameter generated by the valkyrie 
    function when it is passed data in an -s parameter.

 **otaku note: "spiritia" is the term used by the alien Protodevlin to describe
 the energy & morale generated by human music. Specifically, the band "Firebomber's"
 rock anthems.
 
    
#>
### START COPY
param(
    $spiritia,
    $pythonsrc=$null
)
if( $pythonsrc ){
    $Global:CALLER = $pythonsrc
    foreach( $core in (Get-ChildItem "$(($env:MACTEMP -Split ';')[0])\corefuncs\*.ps1" |
    Where-Object{$core.name -ne 'configurations.ps1'})){ . $core.fullname }
    spaceFold
}
## END COPY



## MACROSS automatically sets a global $HELP when users type "help <number>" in
## the main menu, and clears it when your help message finishes. I didn't use
## the standard comment conventions because scripts I wrote for MACROSS aren't meant
## to work outside of MACROSS (accessing customer data, APIs, etc.)
if($HELP){
    cls
    "`n`n"
    w '
    This is example code highlighting some of the features and uses
    for MACROSS.

    Add an "s" to your selection in the main menu, example "4s" if
    this diamond is #4 in the menu, to load an alternate example message.
    
    Hit ENTER to close.' y
    Read-Host
    Exit
}

<#
                            MACROSS GLOBAL VARIABLES
    Some additional global variables in addition to $HELP to be aware of:

        $dyrl_OUTFILES = the local output folder for diamonds to write to
            (located in the entMACROSS root folder)
        $dyrl_RESOURCES = the local resources folder (located in the
            corefuncs folder)
        $dyrl_CONTENT = the content folder specified at setup (by default, it
            is the same as $dyrl_RESOURCES, but you can set it to a different
            location during setup for multiple users to be able to read from 
            the same files in a central location)
        $dyrl_PLUGINS = the local plugins folder where your custom modules
            go (located in the corefuncs folder)
        $dyrl_CONF = the hashtable containing any additional values you created
            during setup; if you only set default configurations, you shouldn't
            ever need to bother with this.
        $dyrl_TMP = the Temp\MACROSS folder located in %LOCALAPPDATA%
        $dyrl_HN0 = your workstation's hostname
        $dyrl_ROBOTECH = tracks whether you have elevated privileges to run admin tasks;
            $false means you can do admin-level things.
#>


 
## Each MACROSS automation is classified with various properties; see the first three lines
## of this file. You can view any of these within the local attributes ($dyrl_LATTS) hashtable. 

## When one diamond calls another with MACROSS' valkyrie function, the calling diamond
## is automatically assigned to the global variable $CALLER; the calling diamond should
## be the one that assigns the primary data to $PROTOCULTURE so other diamonds know to
## investigate or process it.

if($CALLER){

    ## Using the $CALLER value, you can check the calling diamond's macross class properties in the 
    ## "local attributes" global object, $dyrl_LATTS. Use the macross class properties to ensure
    ## your diamond processes data as needed.
    $val = $dyrl_LATTS.$CALLER.valtype
    $lang = $dyrl_LATTS.$CALLER.lang

    ## The w function simplifies powershell's text formatting for you; w also lets you format text with 
    ## underlines, highlights and "no new line" if you need to use different formatting on the same line.
    w "`n`n The powershell diamond is loaded...`n"
    w $CALLER c -i
    w "is a $lang diamond labeled as" g -i
    w "$val" m -i; w ',' g -n
    w "and used MACROSS' valkyrie function to forward a filepath:" g
    w "`n $PROTOCULTURE`n`n" c

    sleep 2

    $h = getHash $PROTOCULTURE md5            ## getHash will return an md5 or sha256 hash of files
    $f = (Get-ChildItem $PROTOCULTURE).Name
    $t = (Get-ChildItem $PROTOCULTURE).CreationTime | Get-Date -f "yyyy/MM/dd hh:mm:ss"
    $file_info = @($f,$h,$t)

    if($lang -eq 'python'){
        ## The kawamori function controls the $PROTOCULTURE value being passed back and forth
        ## between powershell and python, by updating or clearing the local file
        ## corefuncs\pycross\garbage_io\PROTOCULTURE.mac7
        ## In the python macross library, this is all handled in the macross.valkyrie() function.
        kawamori -c $CALLER -v $file_info      ## Send response back to python diamond
    }
    else{
        Return $file_info       ## Send response back to powershell diamond
    }
    
}

## If users add an 's' to their selection in the main menu, it will switch the global variable
## $dyrl_OPT1 to true, which lets you code additional or alternate functionality in your diamond.
elseif($dyrl_OPT1){
    cls
    "`n`n`n Powershell example diamond:"
    w 'Writing your code to watch for the variable $dyrl_OPT1 to be truthy' g
    w "lets you code the diamond with different behaviors.`n`n" g
    
    ## By default, the yorn function uses button prompts to get Yes or No style input, 
    ## but you can use the -n option to instead loop a prompt until the user enters 
    ## whatever key you specify with -l
    yorn -l 'q' -n
    Exit
}

else{
    cls
    "`n"

    ## The $dyrl_OUTFILES path should be convenient for most diamond outputs
    $demopath = "$dyrl_OUTFILES\demo"

    if(-not (Test-Path $demopath)){
        New-Item -Type directory -Path $dyrl_OUTFILES -Name demo | Out-Null
    }

    
    ## The battroid function will give you a nice ascii art title for your diamond
    $title = battroid '  hikaru'

    ## The minmay function will grab some Macross ascii-art you can throw into your diamond for funsies.
    ## You can select a picture between 0 and 11. Enter "splash" in the main menu to view a quick slideshow.
    minmay 0
    sleep 2

    ## The w function simplifies powershell's text formatting for you; w also lets you format text with 
    ## underlines, highlights and "no new line" if you need to use several different colors on the same line.
    ## By default, it adds a space to the front of your string to push it from the edge of the window, but
    ## you can disable that with -n:
    w $title -b y -f k -n
    
    ## The sep function takes a character or set of characters and multiplies them across the 
    ## screen, with a color you choose, to help separate one output from another.
    sep '==' 42 y

    ## The dfInfo function lets you display a few of your diamond's [macross] properties (pulled from
    ## The first three lines of your diamond, see the top of this script for example)
    dfInfo HIKARU

    w "`n This demo shows how to use some of MACROSS' utilities; it will ask you for some random text," g
    w "and send it to a python diamond to encode it. Simple stuff. Hit ENTER to begin." g
    Read-Host
    cls
    "`n`n`n"

    
    ## Assign your investigation/work data globally as $PROTOCULTURE. In this case, I'm using MACROSS' getBlox
    ## function that lets users dump huge blocks of text into a variable for processing. There is a similar
    ## function called getFile that lets users select files or folders instead of entering text.
    $Global:PROTOCULTURE = getBlox -t 'Example automations' -i 'To begin, enter some text for the demo'
    
    
    ## The noBOM function is a less-wordy way of getting around powershell's idiotic addiction to 
    ## BOM-encoding all its out-file writes.
    noBOM -t $PROTOCULTURE -f "$demopath\demo.txt"

    $block1 = "$(' '*27)MACROSS automation flow"
    $block2 = @(
        "Your automation does whatever it needs to do, but instead of coding extra tasks, you can search for existing automations within MACROSS written by yourself or your team to enrich or further process your diamond's data:"
        'The findDF function finds relevant diamonds, and the valkyrie function forwards and retrieves data between them, with all automations giving priority to data assigned to the global variable $PROTOCULTURE'
        'MACROSS provides numerous utilities to quickly reformat data onscreen or into txt reports & spreadsheets'
    )
    

    ## At startup, MACROSS performs a quick check for administrative privileges, and uses the global value
    ## $dyrl_ROBOTECH so your automation can skip any tasks that require elevated permissions. 
    if($dyrl_ROBOTECH){ $block3 = 'r~You are not logged in as an admin.' }
    else{ $block3 = 'g~You are logged in as an admin.' }

    ## If you enabled logging during setup, the errLog function can record activity for your auditing & troubleshooting;
    ## Access logs from the debugger by entering "debug" in the main menu. If logging is disabled, errLog doesn't do anything.
    errLog INFO 'HIKARU.main' "$USR ran the demo diamond"

    ## The setLocal function lets you grab network information so that you don't have to hardcode full IPs into
    ## your diamonds.
    $netinfo = setLocal
    $enclave = $netinfo[0]  ## Determine which enclave you're on
    $octets = $netinfo[1]   ## The network's leading IPv4 octets
    $hextets = $netinfo[2]  ## The network's leading IPv6 hextets
    $domain = $netinfo[3]   ## The network's domain
    $host_ip = setLocal -m  ## You can grab just your local IP


    ## The screenResults function takes large blocks of text and formats them into columns. Highlight different columns
    ## by adding the first letter of a color to your value with a ~, like "c~" for cyan.
    screenResults "$block1"
    $i = 1
    foreach($b in $block2){
        screenResults "$i`." $b
        $i++
    }
    screenResults 'Your input' "w~$PROTOCULTURE" 'c~Saved as $PROTOCULTURE'
    screenResults 'Privilege level' $block3
    screenResults "`$PROTOCULTURE value was saved to $demopath\demo.txt"
    screenResults 'NETWORK INFO:' "IP=$host_ip Enclave=$enclave IPv4=$octets IPv6=$hextets Domain=$domain"
    screenResults -e
    "`n`n"

    w 'User inputs saved; hit ENTER to continue.' g -i
    Read-Host


    ## You can also search for MACROSS diamonds via the findDF utility, which returns a list of the 
    ## diamonds matching your filters. This function has an option, -e, that forces exact matches of
    ## the -v values (you can search multiple values by separating them with commas); the default 
    ## just finds partial matches for comma-separated -v values. This functionality relies on the information 
    ## you've put in the first three lines of your MACROSS diamonds!
    $relevant_tools = [array]$(findDF -v 'encode,example' -l 'python')

    ## This example will give back the name of this file (HIKARU), specifying the *exact* .valtype value with "-e"
    $original = findDF -v 'macross code example' -l 'powershell' -e


    ## The mkList function generates an array you can use to collect larger datasets. I got sick of
    ## manually typing the .NET method for creating lists.
    $response = mkList


    ## Automatically alert all the relevant diamonds that there is data to process by using the
    ## valkyrie function, which requires the $diamond you are calling, as well as the name of your diamond.
    ## The valkyrie function is also written to accept an additional arg using -o, if the called diamond
    ## is written to process a value with, or instead of, $PROTOCULTURE.
    foreach($df in $relevant_tools){
        $var = valkyrie $df HIKARU       # You could send another param to the diamond using "-s $other_value" if needed
        $response.add($var) | Out-Null
    }

    ## The yorn function lets you get quick responses to select the next branch or task
    $q = @("MACROSS' yorn function lets you prompt users for various responses.",
    "Click OK to send the text you entered to a python automation.") -Join ' '

    yorn -l 'Example Script (yorn)' -q $q -b 0 -i 64 | Out-Null


    ## The screenResultsAlt function is an alternate way to present diamond results when you don't expect paragraphs
    ## of text. It takes a -(h)eader for the main object you're parsing, a (-k)ey to name each item, and a -(v)alue
    ## for the actual result of whatever you processed.
    screenResultsAlt -h "Found $df using the findDF function..." -k 'Original Script' -v $original
    screenResultsAlt -k 'Collab Script' -v $df
    screenResultsAlt -k 'Language' -v $dyrl_LATTS.$df.lang
    screenResultsAlt -k 'Access Tier' -v $dyrl_LATTS.$df.access
    screenResultsAlt -k 'w~Original value' -v "w~$PROTOCULTURE"
    screenResultsAlt -k 'c~Processed value' -v "r~$($response[0])"
    screenResultsAlt -e

    sleep 3

    ## This yorn call is tweaked to show different messages and buttons
    $yn = yorn -l 'Example Script (sheetz)' -q "Would you like to write these outputs into a test spreadsheet?" -i 32 -b 4

    ## MACROSS' sheetz utility lets you write outputs to a spreadsheet, including highlights for values of interest;
    ## like the screenResults function, using "<letter>~" allows colorizing cells and text within the spreadsheet.
    if($yn -eq 'Yes'){
        w 'Generating spreadsheet, please wait a few moments. ' -b g -f k 
        w 'Do not click inside the sheet as it writes...      ' -b g -f k 
        "`n"
        $e = 'HIKARU'
        $header = 'Script Name,Language,Access Tier,Data'
        $cells = "$e,y~k~$($dyrl_LATTS.$e.lang),$($dyrl_LATTS.$e.access),g~k~$PROTOCULTURE,$df,g~k~$($dyrl_LATTS.$df.lang),$($dyrl_LATTS.$df.access),b~w~$($response[0])"
        
        ## At a minimum, sheetz requires a -o output filename, and a -v comma-separated value string. The -h param can
        ## be either names of columns, or the number of columns you want to write to. Without -h, the -v values will all
        ## just be written in their own rows on Column A.
        sheetz -o 'macross_test_sheet' -h $header -v $cells
        w 'Spreadsheet was saved to' g
        w $dyrl_OUTFILES
    }

    "`n"
    
    ## The gerwalk function is a key generator that allows you to protect a block of data, 
    ## like a list of servers or whatever. It generates a key that can only be reverted to 
    ## plaintext within an active MACROSS session. You can call this function to create keys 
    ## from the main menu by entering "newkey".
    w 'MACROSS provides a key generator that you can use to protect blocks of text.' g
    w ' Hit ENTER to generate a demo key:' g
    Read-Host

    ## This generates a protected key using "demo key" as a label:
    gerwalk 'demo key' -g
    
    while($true){
        w "Copy & paste the new key id here: " g -i
        $demokey = Read-Host
        $keyfile = $demokey.Trim() -replace "(^.* | .*$)" -replace "'" -replace "$",'.ger'
        $keyfile = "$dyrl_RESOURCES\$keyfile"
        if(Test-Path -Path $keyfile){ Break }
    }

    ## This decodes the key and gives back the original plaintext
    $retrieved = gerwalk $demokey

    $example_content = $(Get-Content -raw $keyfile)
    $full = $example_content.length
    $example_content = $example_content.Substring(0,70)
    rv $full


    w "`n`n MACROSS keys are kept in" g
    w "    $dyrl_RESOURCES"
    w "and stores your data as" g
    w "$example_content... ($full more bytes)" y
    w "`n Your diamond would use 'gerwalk $demokey' to get back" g
    w "$retrieved`n" y
    w "Hit ENTER to run MACROSS' houseKeeping function and delete the demo file." g
    Read-Host
    Remove-Item $keyfile

    ## The houseKeeping function lets your diamond present the location of previous
    ## outputs that might need to be deleted. It requires a report path and the name
    ## of your diamond.
    houseKeeping -r "$demopath\*txt" -d HIKARU
    Remove-Item $demopath

    w 'Make sure to review this powershell code for examples of how to use MACROSS. You 
 can also enter "debug" in the main menu to view all the available utilities and test 
 them, or enter "config" to modify the default configs you created at setup.

 Hit ENTER to exit.' g
    Read-Host
    
}

<#  FINAL NOTES
 The global values $dyrl_CONF (the items you added to configuration during MACROSS' initial
 setup), $CALLER and $PROTOCULTURE are automatically cleared out every time MACROSS' main 
 menu loads. If you did not add configuration values beyond the default items that the
 setup menu prompted you for, you don't even need to worry about $dyrl_CONF.
 
 $PROTOCULTURE is the only one of these that you need to assign manually as needed.

 Type "debug" in the main menu to load the debugger and view all the available utilities.

#>

