#_SDF1 Example Powershell Automation
#_ver 0.1
#_class user,common,macross code example,powershell,hisurfadvisory,2,string


<#
    IMPORTANT!
    The first three lines of any MACROSS diamond automation MUST match the above!
    line 1 = brief description of your diamond; this displays in the main menu
    line 2 = the version number
    line 3 = the properties identifying your script to MACROSS:
        field 1 (.priv): the lowest level of privilege required to execute the script (user vs. admin)*
        field 2 (.access): if you enabled access controls, this needs to specify tier1/tier2/tier3, or "common"
            to make available to all tiers. Even if not using access control, this field is required. Note that
            this is strictly a convenience feature for auto-distribution to varied user's needs from a
            central repo; this is easily bypassed, so not really a "control".
        field 3 (.valtype): what kind of task or data your script works on
        field 4 (.lang): the script's language powershell or python
        field 5 (.auth): the author
        field 6 (.evalmax): the max number of parameters/arguments the script can evaluate (not counting
            the global $PROTOCULTURE value)
        field 7 (.rtype): what format your script responds in, if any

    For scripts to collaborate on the same data, assign your working data to the var $Global:PROTOCULTURE and
    make sure all scripts are coded to act on this data automatically when appropriate. This var will be
    automatically killed by MACROSS when the main menu loads again.

    *You can have scripts containing privileged functions that are still usable without them. Simply
    add a truthy check for $ROBOTECH; if it is $true, the user does not have admin privilege to execute
    it.

#>


## Type "debug" in the main menu to see help files for all of MACROSS's utilities and test them out.



########################## TO WORK WITH PYTHON ####################################
<#
 The following code must be copied verbatim* into any powershell scripts that
 expect to receive calls from python scripts!

 $deculture is any optional value that needs to be processed instead of
 or in addition to $PROTOCULTURE.

 The $pythonsrc param will be the name of the calling python script. In this example
 we use it to set the global $CALLER, first so we can look at the calling diamond's
 properties, and also in case this script needs to further process
 $PROTOCULTURE by calling another powershell diamond.

 The spaceFold function loads all of MACROSS's resources in a temporary
 powershell session to process the python script's request.

    *$deculture is not limited to python <-> powershell interactions; it can be used
    for any powershell script as this is a parameter generated by the collab
    function when it is passed data in an -o parameter.
#>
### START COPY
param(
    $deculture,
    $pythonsrc=$null
)
if( $pythonsrc ){
    $Global:CALLER = $pythonsrc
    foreach( $core in (Get-ChildItem "$(($env:TEMPENV -Split ';')[0])\corefuncs\*.ps1" |
    Where-Object{$core.name -ne 'configurations.ps1'})){ . $core.fullname }
    spaceFold
}
## END COPY



## MACROSS automatically sets a global $HELP when users type "help <number>" in
## the main menu, and clears it when your help message finishes. I didn't use
## the standard comment conventions because my automations were specific to
## MACROSS's framework.
if($HELP){
    cls
    "`n`n"
    w '
    This is example code highlighting some of the features and uses
    for MACROSS.

    Add an "s" to your selection in the main menu, example "4s" if
    this script is #4 in the menu, to load an alternate example message.

    Hit ENTER to close.' y
    Read-Host
    Exit
}

<#
                            MACROSS GLOBAL VARIABLES
    Some additional global variables in addition to $HELP to be aware of:

        $dyrl_OUTFILES = the local output folder for diamonds to write to
            (located in the MACROSSce root folder)
        $dyrl_RESOURCES = the local resources folder (located in the
            corefuncs folder)
        $dyrl_CONTENT = the content folder specified at setup (by default, it
            is the same as $dyrl_RESOURCES, but you can set it to a different
            location during setup for multiple users to be able to read from
            the same files in a central location)
        $dyrl_PLUGINS = the local plugins folder where your custom modules
            go (located in the corefuncs folder)
        $dyrl_PYNET = the MACROSS-specific python executable path; provides several
            3rd-party libraries including macross, numpy, pandas, pdfminer,
            & paramiko
        $dyrl_TMP = the Temp\MACROSS folder located in %LOCALAPPDATA%
        $dyrl_HN0 = your workstation's hostname
        $ROBOTECH = tracks whether you have elevated privileges to run admin tasks;
            $false means you can do admin-level things.
#>



## Each MACROSS automation is tracked using the [macross] class; see the first three lines
## of this file. You can view any of these within the local attributes ($dyrl_LATTS) hashtable,
## or enter "debug" in the main menu and then execute the TL function.

## When one diamond calls another with MACROSS's collab function, the calling diamond
## is automatically assigned to the global variable $CALLER; the calling script should
## be the one that assigns the primary data to $PROTOCULTURE so other diamonds know to
## investigate or process it.

if($CALLER){

    ## Using the $CALLER value, you can check the calling diamond's macross class attributes in the
    ## "local attributes" global object, $dyrl_LATTS. Use the macross class to ensure your diamond
    ## processes data as needed.
    $val = $dyrl_LATTS.$CALLER.valtype
    $lang = $dyrl_LATTS.$CALLER.lang


    ## The w function simplifies powershell's text formatting for you; w also lets you format text with
    ## underlines, highlights and "no new line" if you need to use different formatting on the same line.
    "`n`n`n"
    if($lang -eq 'python'){ w 'You are now in the powershell script MYLENE.ps1.' g }
    w "Powershell can see that $CALLER" g -i
    w "is a $lang script labeled as" g
    w "$val" m -i; w ',' g -n -i
    w "and used MACROSS's collab function to`n forward a filepath:" g
    w "`n $PROTOCULTURE`n`n" c

    sleep 2

    $h = getHash $PROTOCULTURE md5            ## getHash will return an md5 or sha256 hash of files or strings
    $f = (Get-ChildItem $PROTOCULTURE).Name
    $t = (Get-ChildItem $PROTOCULTURE).CreationTime | Get-Date -f "yyyy/MM/dd hh:mm:ss"
    $file_info = @($f,$h.toUpper(),$t)

    if($lang -eq 'python'){
        ## The pyNET function controls the $PROTOCULTURE value being passed back and forth
        ## between powershell and python, by updating or clearing the local file
        ## 'corefuncs\pynet\garbage_io\PROTOCULTURE.vf1'.
        ## In the python macross library, this is all handled in the macross.collab() function
        ## (python has no macross.pyNET() function to worry about)
        pyNET -c $CALLER -v $file_info
    }
    else{
        Return $file_info       ## Send response back to powershell script
    }

}

## If users add an 's' to their selection in the main menu, it will switch the global variable
## $dyrl_OPT1 to true, which lets you code additional or alternate functionality in your diamond.
elseif($dyrl_OPT1){
    cls
    "`n`n`n Powershell example script:"
    w 'Writing your code to watch for the variable $dyrl_OPT1 to be truthy' g
    w "lets you code the diamond with different behaviors.`n`n" g

    ## By default, the yorn function uses button prompts to get Yes or No style input,
    ## but you can use the -n option to instead loop a prompt until the user enters
    ## whatever string you specify with -l
    yorn -l 'q' -n
    Exit
}

else{
    cls
    "`n"

    ## The minmay function displays one of twelve Macross ascii art images. Supply a number
    ## from 0 to 11. Enter "screens" in the main menu to view a slideshow of available art and
    ## their numbers.
    minmay 6
    sleep 2
    cls

    ## The $dyrl_OUTFILES path should be convenient for most script outputs. This is located
    ## in the MACROSS root directory with the macross_core & python folders.
    $demo_output = "$dyrl_OUTFILES\demo.txt"


    ## The skyWriter function will give you a nice ascii art title for your script
    $title = skyWriter ' MYLENE'

    ## The w function simplifies powershell's text formatting for you; w also lets you format text with
    ## underlines, highlights and "no new line" if you need to use several different colors on the same line.
    ## By default, it adds a space to the front of your string to push it from the edge of the window, but
    ## you can disable that with -n:
    w $title -b y -f k -n

    ## The sep function takes a character or string of characters and multiplies them across the
    ## screen, with a color you choose, to help separate one output from another.
    sep '==' 42 y

    ## The toolInfo function lets you display a few of your diamond's [macross] properties (pulled from
    ## The first three lines of your script, see the top of this script for example)
    toolInfo MYLENE

    w "`n This demo shows how to use some of MACROSS's utilities; review the code to get" g
    w "an idea of how MACROSS might benefit your automations. Here, we'll ask you for some" g
    w "random text, and send it to a python diamond to encode it. Simple stuff." g
    w "Hit ENTER to begin." g
    Read-Host


    ## Assign your investigation/work data globally as $PROTOCULTURE. In this case, I'm using MACROSS's getBlox
    ## function that lets users dump huge blocks of text into a variable for processing. There is a similar
    ## function called getFile that lets users select files or folders instead of entering text.
    $Global:PROTOCULTURE = getBlox -t 'Example automations' -i 'To begin, enter some text for the demo'

    ## Write to a text file without powershell's annoying addiction to BOM encoding
    noBOM -t $PROTOCULTURE -f $demo_output

    w 'The text you entered was saved in the local directory' g
    w $dyrl_OUTFILES
    w 'which MACROSS tracks as $dyrl_OUTFILES. This makes it easy to do cleanups' g
    w 'with the houseKeeping function later on.' g
    "`n`n"

    $block1 = "$(' '*27)MACROSS automation flow"
    $block2 = @(
        "Your automation does whatever it needs to do, but instead of copy-pasting to other scripts, you can search for existing automations within MACROSS written by yourself or your team to enrich or further process your script's data:"
        'The findDiamond function finds relevant scripts (diamonds), and the collab function forwards and retrieves data between them, with all automations giving priority to data assigned to the global variable $PROTOCULTURE'
        'MACROSS provides several utilities to quickly reformat data onscreen or into txt reports & spreadsheets'
    )


    ## At startup, MACROSS performs a quick check for administrative privileges (a simple active-directory query); if it
    ## fails, the global value $ROBOTECH is set $true so your automation can skip any tasks that require elevated permissions.
    if($ROBOTECH){ $block3 = 'r~You are not logged in as an admin.' }
    else{ $block3 = 'g~You are logged in as an admin.' }

    ## If you enabled logging during setup, the errLog function can record activity for your auditing & troubleshooting;
    ## Access logs from the debugger by entering "debug" in the main menu. If logging is disabled, errLog doesn't do anything.
    errLog INFO 'MYLENE.main' "$USR ran the demo script"

    ## The setLocal function lets you grab network information so that you don't have to hardcode full IPs into
    ## your scripts.
    $netinfo = setLocal
    $my_ip = setLocal -m    ## You can grab just your local IP with -m
    $octets = $netinfo[0]   ## The network's leading IPv4 octets
    $hextets = $netinfo[1]  ## The network's leading IPv6 hextets
    $domain = $netinfo[4]   ## The network's domain
    $enclave = $netinfo[5]  ## Determine which enclave you're on


    ## The screenResults function takes large blocks of text and formats them into columns. Highlight different columns
    ## by adding the first letter of a color to your value with a ~, like "c~" for cyan.
    screenResults "$block1"
    $i = 1
    foreach($b in $block2){
        screenResults "$i`." $b
        $i++
    }
    screenResults 'Your input' "w~$PROTOCULTURE" 'c~Saved as $PROTOCULTURE'
    screenResults 'Privilege level' $block3
    screenResults "`$PROTOCULTURE value was saved to $demo_output"
    screenResults 'NETWORK INFO:' "IP=$my_ip Enclave=$enclave IPv4=$octets IPv6=$hextets Domain=$domain"
    screenResults -e
    "`n`n"


    ## You can supply an output filename with -o if you want screenResults to write this table to a
    ## txt file in the $dyrl_OUTFILES folder instead of printing it to screen.



    w 'User inputs saved; hit ENTER to continue.' g -i
    Read-Host


    ## You can search for MACROSS diamonds via the findDiamond utility, which returns a list of any
    ## diamonds matching your filters. This function has an option, -e, that forces exact matches of
    ## the -v values; the default behavior just finds partial matches for comma-separated -v values. This
    ## functionality relies on the information you've put in the first three lines of your MACROSS scripts!
    [array]$relevant_diamonds = $(findDiamond -v 'encode,example' -l 'python')

    ## This example will give back the name of this file (MYLENE), specifying the *exact* .valtype value with "-e"
    $original = findDiamond -v 'macross code example' -l 'powershell' -e


    ## The yorn function lets you get quick responses to select the next branch or task
    $q = @("MACROSS's yorn function lets you prompt users for various responses.",
    "Click OK to send the text you entered to a python automation.") -Join ' '

    yorn -l 'Example Script (yorn)' -q $q -b 0 -i 64 | Out-Null


    ## The mkList function generates an array you can use to collect larger datasets. I got sick of
    ## manually typing the .NET method for creating lists.
    $response = mkList


    ## Automatically alert all the relevant scripts that there is data to process by using the
    ## collab function, which requires the $diamond you are calling, as well as the name of your diamond.
    ## The collab function can accept an additional arg using -o, if the called diamond
    ## is coded to process a value with, or instead of, $PROTOCULTURE.
    foreach($diamond in $relevant_diamonds){
        $var = collab $diamond MYLENE         # You could add another param using "-o $other_parameter" if needed
        [void]$response.add($var)
    }


    ## The screenResultsAlt function is an alternate way to present script results when you don't expect paragraphs
    ## of text. It takes a (-h)eader for the main object you're parsing, a (-k)ey to name each item, and a (-v)alue
    ## for the actual result of whatever you processed. Use -e to print a final separation line to make it all pretty.
    screenResultsAlt -h "Found $diamond using the findDiamond function..." -k 'Original Script' -v $original
    screenResultsAlt -k 'Collab Script' -v $diamond
    screenResultsAlt -k 'Language' -v $dyrl_LATTS.$diamond.lang
    screenResultsAlt -k 'Access Tier' -v $dyrl_LATTS.$diamond.access
    screenResultsAlt -k 'w~Original value' -v "w~$PROTOCULTURE"
    screenResultsAlt -k 'c~Processed value' -v "r~$($response[0])"  ## This is what the python script sent back
    screenResultsAlt -e

    sleep 3

    ## This yorn call is tweaked to show different messages and buttons
    $yn = yorn -l 'Example Script (sheetz)' -q "Would you like to write these outputs into a test spreadsheet?" -i 32 -b 4

    ## MACROSS's sheetz utility lets you write outputs to a spreadsheet, including highlights for values of interest;
    ## like the screenResults function, using "<letter>~" allows colorizing cells and text within the spreadsheet.
    ## Of course, it requires MS Excel to be installed. MACROSS uses the corefuncs\resources\installed_programs.json
    ## file to scan your system for installed programs, and sets various variable names as $true so you can do checks
    ## before errors happen. In this case, if Excel is installed, the global variable $SHEETZ should be true.
    if($yn -eq 'Yes'){
        w 'Generating spreadsheet, please wait a few moments. ' -b g -f k
        w 'Do not click inside the sheet as it writes...      ' -b g -f k
        "`n"
        $e = 'MYLENE'
        $header = 'Script Name,Language,Access Tier,Data'
        $cells = @(
            $e,
            "y~k~$($dyrl_LATTS.$e.lang)",
            "$($dyrl_LATTS.$e.access)",
            "g~k~$PROTOCULTURE",
            $diamond,
            "g~k~$($dyrl_LATTS.$diamond.lang)",
            "$($dyrl_LATTS.$diamond.access)",
            "b~w~$($response[0])"
        ) -Join '<::>'

        ## At a minimum, sheetz requires a (-o)utput filename, and a (-v)alue string separated by the pattern "<::>".
        ## (the pattern allows for your cell contents to contain commas and other common delimeter characters)
        ## The -h param can be either names of columns, or the number of columns you want to write to. Without -h,
        ## the -v values will all just be written in their own rows in Column A.
        sheetz -o 'macross_test_sheet' -h $header -v $cells
        if(Test-Path "$dyrl_OUTFILES\macross_test_sheet.xlsx"){
            w 'Spreadsheet was saved to' g
            w $dyrl_OUTFILES
        }
        elseif($SHEETZ){    ## This check is set using the corefuncs\resources\installed_programs.json file
            $error[0]
        }
    }


    ## The kawamori function lets you store data in a protected state when there isn't a better way available.
    ## MACROSS will take any value you pass in, and generate an encrypted key that you can use to retrieve that 
    ## data as needed. Call the kawamori function from the main menu by entering "newkey", and copy the key ID
    ## it provides into your script to decrypt the key during a MACROSS session. Encrypted keys are stored in
    ## corefuncs\resources\kawa using .mori files. Delete them when no longer needed.
    "`n`n"
    w 'The kawamori function can protect data for you in the corefuncs\resources\kawa folder.' g
    w 'Hit ENTER to generate a demonstration key.' g
    Read-Host
    kawamori demo_test_data -g -m
    w 'Copy/enter the ID generated by kawamori: ' g -i
    $id = Read-Host

    ## Decrypt mori keys by calling kawamori with the ID:
    $plaintext = kawamori $id
    w "Your decrypted data is " g -i
    w $plaintext y

    w "`n Hit ENTER to run MACROSS's houseKeeping function and delete the demo files." g
    Read-Host

    ## The houseKeeping function lets your script present the location of previous
    ## outputs that might need to be deleted. It requires a report path and the name
    ## of your script.
    houseKeeping -r "$dyrl_OUTFILES\*" -t MYLENE

    w 'Make sure to review this powershell code for examples of how to use MACROSS. You
 can also enter "debug" in the main menu to view all the available utilities and test
 them, or enter "config" to modify the default configs you created at setup.

 Hit ENTER to exit.' g
    Read-Host

}

<#  FINAL NOTES
 $PROTOCULTURE is the only global value in MACROSS that you *must* assign manually as needed.

 MACROSS also tracks $HOWMANY (which I used to count successful operations across multiple
 diamonds) and $RESULTFILE (used to reference any output file that other diamonds might need to
 read) as globals if you want to use these, so that you don't have to worry about cleaning
 them up. But they are not necessary.

 Type "debug" in the main menu to load the debugger and view all the available utilities.

#>





